name: mimi
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: ^0.4.3
  hidden_drawer_menu: ^1.1.1
  circular_profile_avatar: ^0.2.0
  progress_button: ^0.0.2
  flutter_progress_button: ^1.0.0
  date_picker_persian: ^0.1.2
  dropdownfield: ^1.0.1
  dropdown_formfield: ^0.1.0
  material_design_icons_flutter: ^3.2.4096
  titled_navigation_bar: ^3.6.0
  card_selector: ^0.1.0
  flutter_swiper: ^1.1.6
  barcode_flutter: ^1.0.1
  meta:
  flutter_bloc: ^0.21.0
  bottom_navy_bar: ^5.2.0
  flutter_auth_buttons: ^0.5.0
  dartz: ^0.8.7
  pin_code_fields: ^1.1.2
  pinput: ^0.1.10
 
  cloud_firestore: ^0.12.9+4
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  firebase_messaging: ^5.1.5
  flutter_facebook_login: ^2.0.1
  badges: ^1.1.0
  date_picker_timeline: ^1.0.0
  queries: ^0.1.12
  flutter_money_formatter: ^0.8.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  pin_code_text_field: ^1.2.1
  pin_view: ^1.0.1
  font_awesome_flutter:
  country_pickers: ^1.0.2
  country_code_picker: ^1.1.5
  flutter_spinkit: ^3.1.0
  shared_preferences: ^0.5.1+2
  flutter_typeahead: ^1.4.0
  sliding_up_panel: ^0.3.4
  circular_bottom_navigation: ^0.9.1
  flutter_pagewise:
  fancy_bottom_navigation: ^0.3.2
  scoped_model: ^1.0.1
  stripe_payment: ^0.1.0
  equatable:
  bloc:
  giffy_dialog:
  provider:
  progress_hud:
  rxdart:
  device_preview: ^0.1.9-beta
  toast:
  get_it:
  flare_flutter:
  smart_flare:
  modal_progress_hud:
  liquid_pull_to_refresh: 
  flushbar:
  sms_autofill: ^1.1.0 
  pin_input_text_field:
  google_sign_in:

    
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
   - assets/circle.flr2d
   - assets/mimi_flare.flr
   - assets/pathanimation.flr
   - assets/done-checkmark.flr
   - assets/red_success.flr
   - assets/check_success.flr
   - assets/mobyle.flr
   - assets/green.flr
   - assets/tigopesa.jpg
   - assets/TigoPesa-logo.png
   - assets/airtel.png
   - assets/mpesaIcon.png
   - assets/airtel2.png
   - assets/vodacom-mpesa.png
   - assets/voda.jpg
   - assets/airtel-money.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto/Roboto-Bold.ttf
    #     - asset: fonts/Roboto/Roboto-Medium.ttf
    #     - asset: fonts/Roboto/Roboto-Regular.ttf
    
    - family: OpenSans
      fonts:
        #- asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-SemiBold.ttf
    #- asset: fonts/OpenSans/OpenSans-Light.ttf
    
    - family: NothingYouCouldDo
      fonts:
        - asset: fonts/NothingYouCouldDo-Regular.ttf

    - family: NotoSerif
      fonts:
        - asset: fonts/NotoSerif-Regular.ttf
        - asset: fonts/NotoSerif-Bold.ttf
        

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
